# -*- coding: utf-8 -*-
"""Assignment7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pr42wNUOhOdW9Td-gAAKoZVcVpLNUGaw
"""

import scipy.integrate as integrate
import matplotlib.pyplot as plt
import numpy as np


#Let 
alpha = 3
beta = 3

#Probabiltiy distrubution function f(x)
def f(x) : 
  return ( alpha*(x**(alpha -1)) + beta*(x**(beta-1) )*np.exp(-(x**alpha) - (x**beta)) )



x = np.arange(1,100,1) 

#Cummulative distrubution function 
def cdf(x):
  res = np.zeros_like(x)
  for i,val in enumerate(x):
        res[i] = integrate.quad(f,0,val)[0] 
  return res

#Hazard function h(x)
def h(x):
  return f(x)/(1-cdf(x))

fig = plt.figure()

# plot the function
plt.plot(x,h(x), 'r')

# show the plot
plt.show()

#From graph , h(x) is an increasing function.