# -*- coding: utf-8 -*-
"""Assignment3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sZJU8osrqFTvg337q5CTC_o7hzp5iBAn
"""

from scipy.stats import expon
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots(1, 1)

x = np.linspace(0,10, 10000)

ax.plot(x, expon.pdf(x,scale = 5/3),'r', label='theoritical')
rv = expon()
r = expon.rvs(scale = 5/3,size=1000)
ax.hist(r, density=True)
ax.legend(loc='best', frameon=False)

plt.title("Theory vs Simulation for exponential random variable")
plt.xlabel("x")
plt.ylabel("Probability density function")
plt.show()