# -*- coding: utf-8 -*-
"""Assignment3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sZJU8osrqFTvg337q5CTC_o7hzp5iBAn
"""

from scipy.stats import expon
import matplotlib.pyplot as plt
import numpy as np

# For exponential distrubtion f(x) = lambda*e^(-lambda*x)
# For Y, lambda = 3/5
x=np.arange(0,10,0.1)
y = expon.pdf(x,scale=5/3) #scale = 1/lambda
plt.plot(x,y)
plt.title("Exponential probability distrubution")
plt.xlabel("x")
plt.ylabel("Probability density function")
plt.show()

# Finding Area under curve
def f(x):  
  return expon.pdf(x,scale=5/3)

x_i=0
x_f=1000
N=10000
Area=0
dx=(x_f-x_i)/N
while x_f>=x_i:
    dA=f(x_i)*dx
    x_i=x_i+dx
    Area=Area+dA

print(f'Area under the curve is {Area} aproximately ')