# -*- coding: utf-8 -*-
"""Assignment5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AHomVo7Fhr1KsN0yUpF4A6HrU5QYQKj_
"""

#n = total number of trails
#k = number of heads

#Let n=3
n=3
k=0
favourable=0
while k<n:
  if abs( k-(n-k) )== n-3:
    favourable +=1
  k+=1

if favourable==0:
  print('Probability when n=3 is 0')

n=4
k=0
favourable=0
while k<n:
  if abs( k-(n-k) )== n-3:
    favourable +=1
  k+=1
if favourable==0:
  print('Probability when n=4 is 0')