# -*- coding: utf-8 -*-
"""Assignment5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AHomVo7Fhr1KsN0yUpF4A6HrU5QYQKj_
"""

from scipy.stats import binom
#n = total number of trails
#k = number of heads

#Let n=3
n=3
k=0
Probability=0
while k<n:
  if abs( k-(n-k) )== n-3:
    Probability+= binom.pmf(n,1/2,k)
  k+=1
print(f'Probability when n=3 is {Probability}')
#Let n=4
n=4
k=0
Probability=0
while k<n:
  if abs( k-(n-k) )== n-3:
    Probability+= binom.pmf(n,1/2,k)
  k+=1
print(f'Probability when n=4 is {Probability}')