# -*- coding: utf-8 -*-
"""Assignment6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OR13-23L9DRKV3R0FRzFnPAQ88TjiNjd
"""

from scipy.stats import binom

#n = total number of trails
n=4
#k = number of heads
k=3

#Theoritical
theoritical_prob = binom.pmf(k,n,1/2)

# Calculated

size = int(1e7)
# E be event of getting 3 heads 

data_E = binom.rvs(n=4 , p = 1/2 ,size = size )
count_E=0
for i in range(size):
     if data_E[i]==3:
         count_E +=1
    

calc_prob = count_E/size

print(f'Values of Theoritacal and calculated probabilities are {theoritical_prob} and {calc_prob} respectively')